#
# Makefile
#

all:

clean:

install:
	install -m 644 root_ca.pem $(CERTSDIR)/arsoft_root_ca_1.crt
	install -m 644 root_ca_com.pem $(CERTSDIR)/arsoft_root_ca_2.crt
	install -m 644 root_ca_com_1.pem $(CERTSDIR)/arsoft_root_ca_3.crt
	install -m 644 ssl_ca_com.pem $(CERTSDIR)/arsoft_ssl_ca_1.crt
