#!/bin/bash
# list missings

cd /tmp/buildd/*/debian/..

echo "##### STARTING LIST-MISSING HOOK"
cat debian/rules | grep kde4.mk > /dev/null 2>&1
if [ "$?" == "0" ] || [ -e debian/cdbs ]; then
    echo "Using the list missing coming with kde4.mk"
    make -f debian/rules list-missing

elif [ -e /usr/share/pkg-kde-tools/qt-kde-team/2/list-missing.mk ]; then
    echo "Using the list missing coming with dhmk"
    dqk_dir=1 make -f /usr/share/pkg-kde-tools/qt-kde-team/2/list-missing.mk list-missing

else
    echo "Installing pkg-kde-tools and using the list missing coming with dhmk"
    apt-get install -y --force-yes pkg-kde-tools
    dqk_dir=1 make -f /usr/share/pkg-kde-tools/qt-kde-team/2/list-missing.mk list-missing
fi
