#!/bin/sh

if [ $POOL ]; then
    if [ -z $POOLDIR ]; then
        POOLDDIR=/usr/src/deb/pool
    fi

    cd $POOLDIR
    if [ "$?" != "0" ]; then
        echo "Pool directory not available!!!!!!!"
        exit 1
    fi

    d=`pwd`
    echo $d
    grep "$d" /etc/apt/sources.list > /dev/null 2>&1

    if [ "$?" != "0" ]; then
        echo "deb file:$d ./" >> /etc/apt/sources.list
        echo "APT::Get::AllowUnauthenticated 1;" >> /etc/apt/apt.conf.d/allow-unauthenticated

        release=`grep DISTRIB_CODENAME /etc/lsb-release | cut -d = -f 2`
        mkdir -p $d/dists/$release/
        ln -s $d $d/dists/$release/binary-i386
        ln -s $d $d/dists/$release/binary-amd64
        ln -s $d $d/dists/$release/binary-armel
        ln -s $d $d/dists/$release/binary-lpia
    fi

    dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
fi
