#!/bin/bash
# ICE ICE BABY!

# To use this script you will need to export ICECC_VERSION in your pbuilderrc to
# a fixed somewhat unique path where your icecc toolchain can be put.
# e.g. export ICECC_VERSION=/tmp/icecc-gcc.tar.gz
#
# Additionally PATH must be enhanced with a preceeding /usr/lib/icecc/bin
# e.g.  export PATH=/usr/lib/icecc/bin:${PATH}

cd /
apt-get install -y --force-yes icecc file || exit 0

cd /tmp
if [ -x /usr/bin/icecc ]; then
    nativetarsum=`icecc --build-native | tail -1 | cut -d ' ' -f 2`
    mv "$nativetarsum" "$ICECC_VERSION"
fi

# for meup in `ls /usr/lib/ccache`; do
#     echo "#!/bin/sh
#           export CCACHE_PATH=/usr/lib/icecc/bin
#           export PATH=/usr/lib/icecc/bin:/usr/sbin:/usr/bin:/sbin:/bin
#           ccache $meup \"\$@\"" > /usr/lib/ccache/$meup
#     chmod +x /usr/lib/ccache/$meup
# done
