#!/bin/sh

DISTRIB_CODENAME=`awk -F '=' '/DISTRIB_CODENAME/ {print$2}' /etc/lsb-release`
cat > /etc/apt/sources.list.d/ubuntu-updates.list << EOF
deb http://archive.ubuntu.com/ubuntu/ $DISTRIB_CODENAME-updates main universe restricted multiverse 
deb-src http://archive.ubuntu.com/ubuntu/ $DISTRIB_CODENAME-updates main universe restricted multiverse
EOF
