#!/bin/sh
dmiinfo=`LANG=C dmidecode 2>/dev/null`
RES=$?
if [ $RES -ne 0 ]; then
	echo "Failed to retrieve DMI information (error $RES)."
elif [ -z "$dmiinfo" ]; then
	echo "No DMI information available."
else
	echo "$dmiinfo" | awk ' /Base Board Information/ {flag=1;print $0; next} /^[A-Z]/{flag=0} flag { print }'
fi

