#!/bin/bash
quiet=0
verbose=0
compile_only=0
variables=0
tplfile=''

function usage() {
	echo "puppet-template-check [OPTIONS] <templatefile>"
	echo "  -h,--help          this help message"
	echo "  -v,--verbose       enables verbose output"
	echo "  -q,--quiet         disable all output messages"
	echo "  -S                 syntax check only"
	exit 0
}

# parse command line arguments
while [ $# -ne 0 ]; do
	case "$1" in
		"-?"|"-h"|"--help") usage;;
		"-S") compile_only=1; ;;
		"-q"|"--quiet") quiet=1; ;;
		"-v"|"--verbose") verbose=1; ;;
		"-l"|"--variables") variables=1; ;;
		*)
			if [ -z "$tplfile" ]; then
				tplfile="$1"
			else
				echo "Too many arguments: $1" 1>&2
				exit 1
			fi
		;;
	esac
	shift
done

if [ $variables -ne 0 ]; then
	/usr/bin/erb -x -T '-' "$tplfile" | /usr/bin/grep -E -o '\( [a-zA-Z_]+ \).to_s' | /usr/bin/awk '{print$2}'
fi

if [ $compile_only -eq 0 ]; then
	/usr/bin/erb -x -T '-' "$tplfile" | /usr/bin/ruby -c
else
	/usr/bin/erb -x -T '-' "$tplfile"
fi

