#!/bin/bash

HOSTS_FILE='/etc/hosts'

network_update_conf() {

	verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update "127.0.0.1" localhost.localdomain localhost
	if [ ! -z "$domain_name" ]; then
		verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update "127.0.1.1" "${host_name}.${domain_name}" "$host_name"
		verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update "::1" "${host_name}.${domain_name}" "$host_name" ip6-localhost ip6-loopback
	else
		verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update "127.0.1.1" "$host_name"
		verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update "::1" "$host_name" ip6-localhost ip6-loopback
	fi
}

case $reason in
	# events from dhclient
	BOUND|RENEW|REBIND|REBOOT)
		network_update_conf
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up|hostname)
		network_update_conf
		;;
    down|vpn-down|dhcp4-change|dhcp6-change)
        ;;
esac
