#!/bin/bash

HOSTS_FILE='/etc/hosts'

network_update_conf() {

	local update_opts="127.0.0.1=localhost.localdomain,localhost"
	if [ ! -z "$domain_name" ]; then
		update_opts="$update_opts 127.0.1.1=${host_name}.${domain_name},$host_name"
		update_opts="$update_opts ::1=${host_name}.${domain_name},$host_name,ip6-localhost,ip6-loopback"
	else
		update_opts="$update_opts 127.0.1.1=$host_name"
		update_opts="$update_opts ::1=$host_name,ip6-localhost,ip6-loopback"
	fi
	verbose_exec "/usr/bin/managehosts" -f "$HOSTS_FILE" update $update_opts
}

case $reason in
	# events from dhclient
	BOUND|RENEW|REBIND|REBOOT)
		network_update_conf
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up|hostname)
		network_update_conf
		;;
    down|vpn-down|dhcp4-change|dhcp6-change)
        ;;
esac
