#!/bin/bash

apt_update_conf() {
	local newproxy=''
	if [ ! -z "$domain_name" ]; then
		local srv_record=`get_dns_srv_record 'apt-proxy' 'tcp'`
		if [ ! -z "$srv_record" ]; then
			local srv_name="${srv_record% *}"
			local srv_port="${srv_record##* }"
			if [ ! -z "$srv_name" ]; then
				newproxy="http://${srv_name}:${srv_port}"
			fi
		fi
	fi
	log_info "apt-proxy=$newproxy"
	verbose_exec "/usr/bin/apt-proxy" set "$newproxy"
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)
		if [ $interface != 'lo' ]; then
			apt_update_conf
		else
			true
		fi
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up|dhcp4-change|dhcp6-change)
		if [ $interface != 'lo' ]; then
			apt_update_conf
		else
			true
		fi
		;;
    down|vpn-down|hostname)
        ;;
esac
