#!/bin/bash
KRB5_CONF='/etc/krb5.conf'
#KRB5_CONF_ORG='/var/run/krb5.conf'

heimdal_check_server() {
	if [ ! -z "$domain_name" ]; then
		newrealm=`get_dns_txt_record "_kerberos.$domain_name."`
	fi

	if [ ! -z "$newrealm" -a -f "$KRB5_CONF" ]; then
		log_info "newrealm=$newrealm"
		tmp=$(mktemp "$KRB5_CONF.XXXXXX") || return
		chmod --reference="$KRB5_CONF" "$tmp"
		chown --reference="$KRB5_CONF" "$tmp"
		(
			sed -r \
				-e "s/^ *(default_realm) *=.*$/\1 = $newrealm/" \
				"$KRB5_CONF"
		) >>"$tmp"
		if [ $? -eq 0 ]; then
			mv "$tmp" "$KRB5_CONF"
		fi
	fi
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)
		heimdal_check_server
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up|dhcp4-change|dhcp6-change)
		heimdal_check_server
		;;
    down|vpn-down|hostname)
        ;;
esac
