#!/bin/bash

HOSTS_FILE='/etc/hosts'

network_update_conf() {

	if [ ! -z "$domain_name" ]; then
		verbose_exec "$scriptdir/managehosts" -f "$HOSTS_FILE" update "127.0.0.1" "${host_name}.${domain_name}" "$host_name" localhost.localdomain localhost
		verbose_exec "$scriptdir/managehosts" -f "$HOSTS_FILE" update "::1" "${host_name}.${domain_name}" "$host_name" localhost.localdomain6 localhost6
	else
		verbose_exec "$scriptdir/managehosts" -f "$HOSTS_FILE" update "127.0.0.1" "$host_name" localhost.localdomain localhost
		verbose_exec "$scriptdir/managehosts" -f "$HOSTS_FILE" update "::1" "$host_name" localhost.localdomain6 localhost6
	fi
}

case $reason in
	# events from dhclient
	BOUND|RENEW|REBIND|REBOOT)
		network_update_conf
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up|hostname)
		network_update_conf
		;;
    down|vpn-down|dhcp4-change|dhcp6-change)
        ;;
esac
