#!/bin/bash

NTP_CONF=/etc/ntp.conf
NTP_DHCP_CONF=/var/lib/ntp/ntp.conf.dhcp
SYSTEMD_TIMESYNCD_CONF=/etc/systemd/timesyncd.conf
SYSTEMD_TIMESYNCD_DEFAULT_NTP='ntp.ubuntu.com 0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org'


ntp_server_restart() {
	invoke-rc.d ntp try-restart
}

ntp_servers_setup_remove() {
	if [ ! -e $NTP_DHCP_CONF ]; then
		return
	fi
	rm -f $NTP_DHCP_CONF
	ntp_server_restart
}


ntp_servers_setup_add() {
	if [ -z "$ntp_servers" ]; then
		ntp_servers_setup_remove
		return
	fi

	tmp=$(mktemp "$NTP_DHCP_CONF.XXXXXX") || return
	chmod --reference=$NTP_CONF $tmp
	chown --reference=$NTP_CONF $tmp

	log_info "ntp_servers_setup_add ntp_servers=$ntp_servers"
	(
	  echo "# This file was copied from $NTP_CONF with the server options changed"
	  echo "# to reflect the information sent by the DHCP server.  Any changes made"
	  echo "# here will be lost at the next DHCP event.  Edit $NTP_CONF instead."
	  echo
	  echo "# NTP server entries received from DHCP server"
	  for server in $ntp_servers; do
		echo "server $server iburst"
	  done
	  echo
	  sed -r -e '/^ *(server *[^1][^2][^7]\.|peer).*$/d' $NTP_CONF
	) >>$tmp
	if [ -f "$NTP_DHCP_CONF" ]; then
		if ! /usr/bin/diff -q "$tmp" "$NTP_DHCP_CONF" > /dev/null; then
			mv "$tmp" "$NTP_DHCP_CONF"
			ntp_server_restart
			log_info "ntp_servers_setup_add restart ntp server"
		else
			# remove temp file because we no longer need it
			rm "$tmp"
		fi
	else
		mv "$tmp" "$NTP_DHCP_CONF"
		ntp_server_restart
		log_info "ntp_servers_setup_add restart ntp server"
	fi
}

timesyncd_restart() {
	systemctl restart systemd-timesyncd.service
}

timesyncd_stop() {
	systemctl stop systemd-timesyncd.service
}

timesyncd_setup_remove() {
	if [ ! -e $SYSTEMD_TIMESYNCD_CONF ]; then
		return
	fi
	log_info "timesyncd_setup_remove"
	tmp=$(mktemp "$SYSTEMD_TIMESYNCD_CONF.XXXXXX") || return
	chmod --reference=$SYSTEMD_TIMESYNCD_CONF $tmp
	chown --reference=$SYSTEMD_TIMESYNCD_CONF $tmp
    (
        sed -r \
            -e "s/^#*(FallbackNTP|NTP)=(.*)$/#NTP=\2/" \
            "$SYSTEMD_TIMESYNCD_CONF"
    ) >>"$tmp"
    if [ $? -eq 0 ]; then
        mv "$tmp" "$SYSTEMD_TIMESYNCD_CONF"
        timesyncd_stop
    fi
}

timesyncd_setup_add() {
	if [ -z "$ntp_servers" ]; then
		timesyncd_setup_remove
		return
	fi

	log_info "timesyncd_setup_add ntp_servers=$ntp_servers"
	tmp=$(mktemp "$SYSTEMD_TIMESYNCD_CONF.XXXXXX") || return
	chmod --reference=$SYSTEMD_TIMESYNCD_CONF $tmp
	chown --reference=$SYSTEMD_TIMESYNCD_CONF $tmp
    (
        sed -r \
            -e "s/^#*NTP=.*$/NTP=$ntp_servers/" \
            -e "s/^#*FallbackNTP=.*$/FallbackNTP=$SYSTEMD_TIMESYNCD_DEFAULT_NTP/" \
            "$SYSTEMD_TIMESYNCD_CONF"
    ) >>"$tmp"
    if [ $? -eq 0 ]; then
        mv "$tmp" "$SYSTEMD_TIMESYNCD_CONF"
		timesyncd_restart
    fi
}

case $reason in
	# events from dhclient
	BOUND|RENEW|REBIND|REBOOT|EXPIRE|FAIL|RELEASE|STOP)
		# DO NOTHING HERE because the original dhcp exit script for ntp
		# is executed by the dhclient and this script takes care about
		# the rest.
		;;
	# events from network-manager
	up|vpn-up|dhcp4-change|dhcp6-change)
		if [ $interface != 'lo' ]; then
            if [ -e "$SYSTEMD_TIMESYNCD_CONF" ]; then
                timesyncd_setup_add
            else
                ntp_servers_setup_add
            fi
		else
			true
		fi
		;;
	down|vpn-down|dhcp4-change|dhcp6-change)
		if [ $interface != 'lo' ]; then
            timesyncd_setup_remove
			ntp_servers_setup_remove
		else
			true
		fi
		;;
	hostname)
		;;
esac
