#!/bin/bash

# Detect if the repo config was disabled by distro upgrade and enable if
# necessary.
REPOLINE=$(grep -E "# disabled on upgrade to .*" "/etc/apt/sources.list.d/ppa-aroth.list")
if [ $? -eq 0 ]; then
  DEBIAN_FRONTEND=noninteractive dpkg-reconfigure arsoft-base
fi
