#!/bin/bash

verbose=0
noop=0
all=0
logrotate=0
newline=`echo -e '\n'`
FQDN=`hostname -f`
DOMAIN=`hostname -d`
MYHOSTNAME=`postconf -h myhostname`
FROM="postmaster@$FQDN"
TO="postmaster@$FQDN"
LOGDIR='/var/log'
LOGFILEPATTERN='mail.log*'
PFLOGSUMM_BIN='/usr/sbin/pflogsumm'
PFLOGSUMM_OPTS='--iso_date_time --problems_first --rej_add_from'
SENDMAIL_BIN='/usr/sbin/sendmail'
SUBJECT="$MYHOSTNAME mail statistics of "`LANG=C date -R`

function usage()
{
    echo "postfix-mailstat [OPTIONS] [LOGFILES]"
    echo "    -h, --help      shows this help screen"
	echo "    -v, --verbose   enable verbose output"
	echo "    --noop          do not actually send a mail."
	echo "    --logdir <DIR>  specifies the directory where the log files are kept (default $LOGDIR)"
	echo "    --all           process all found log file and generate report."
	echo "    --logrotate     specify if called from within logrotate."
	echo "  LOGFILES"
	echo "    any number of log files. If none is specified the log files in $LOGDIR are used."
    exit 0
}

function find_latest_logfile()
{
	local LOGDIR="$1"
	local FILEPATTERN="$2"
	
	LOGFILES=`find "$LOGDIR" -type f -name "$FILEPATTERN" -print 2>/dev/null | xargs stat --format '%Y:%n' | sort -nr | cut -d: -f2-`
}

function generate_summary()
{
	if [ -z "$LOGFILES" ]; then
		[ $verbose -ne 0 ] && echo "No logfile named $LOGFILEPATTERN in $LOGDIR found."
		SUMMARY="No logfile named $LOGFILEPATTERN in $LOGDIR found."
	else
		[ $verbose -ne 0 ] && echo "found logfiles $LOGFILES."
		SUMMARY=''
		for f in $LOGFILES; do
			[ $verbose -ne 0 ] && echo "check logfile $f"
			if [ -r "$f" ]; then
				f_ext="${f##*.}"
				if [ "$f_ext" == "gz" ]; then
					[ $verbose -ne 0 ] && echo "zcat \"$f\" | $PFLOGSUMM_BIN $PFLOGSUMM_OPTS 2>/dev/null"
					f_sum=`"zcat "$f" | $PFLOGSUMM_BIN" $PFLOGSUMM_OPTS 2>/dev/null`
				else
					[ $verbose -ne 0 ] && echo "$PFLOGSUMM_BIN $PFLOGSUMM_OPTS 0<\"$f\" 2>/dev/null"
					f_sum=`"$PFLOGSUMM_BIN" $PFLOGSUMM_OPTS 0<"$f" 2>/dev/null`
				fi
			else
				[ $verbose -ne 0 ] && echo "check logfile $f"
				f_sum="Unable to read ${f}${newline}"
			fi
			if [ ! -z "$f_sum" ]; then
				logdate=`LANG=C date -r "$f" -R`
				f_header="Log file: ${f} ($logdate)"
				if [ -z "$SUMMARY" ]; then
					SUMMARY="${f_header}
${f_sum}
" 
				else 
					SUMMARY="${SUMMARY}
${f_header}
${f_sum}
"
				fi
				[ $all -eq 0 ] && break
			fi
		done
	fi
}

# variables used to pass information between functions
LOGFILES=''
SUMMARY=''

# parse command line arguments
while [ $# -ne 0 ]; do
	case "$1" in
		'-?'|'-h'|'--help') usage;;
		'-v'|'--verbose') verbose=1; ;;
		'--noop') noop=1; ;;
		'--logdir') LOGDIR="$2"; shift; ;;
		'--logrotate') logrotate=1; ;;
		'--all') all=1; ;;
		-*)
			echo "invalid option $1" 1>&2
			exit 1
			;;
		*)
			if [ -f "$1" ]; then
				log=`readlink -f "$1"`
				LOGFILES="$LOGFILES $log"
			else
				echo "invalid argument $1" 1>&2
				exit 1
			fi
			;;
	esac
	shift
done

if [ ! -x "$PFLOGSUMM_BIN" ]; then
	echo "$PFLOGSUMM_BIN not available. Please install pflogsum package." 1>&2
	exit 1
else
	if [ -z "$LOGFILES" ]; then
		find_latest_logfile "$LOGDIR" "$LOGFILEPATTERN"
	fi
	generate_summary
	
	if [ ! -z "$SUMMARY" ]; then
		message="To: $TO
From: $FROM
Subject: $SUBJECT


$SUMMARY

"
		[ $verbose -ne 0 ] && echo "$message"
		if [ $noop -eq 0 ]; then
			echo "$message" | "$SENDMAIL_BIN" -t
		fi
	fi
	exit 0
fi
