.PHONY: all

all:

clean:

install:
#	mkdir -p $(DESTDIR)/etc/network/if-down.d
#	install -m 0755 -o root -g root network/lo-down-script $(DESTDIR)/etc/network/if-down.d/00-lo-down
#	mkdir -p $(DESTDIR)/etc/network/if-up.d
#	install -m 0755 -o root -g root network/lo-up-script $(DESTDIR)/etc/network/if-up.d/zz-lo-up
	install -m 0755 -o root -g root find-snmp-devices $(DESTDIR)/usr/bin/find-snmp-devices
