#!/bin/bash

BACKUPDIR='/local/backup/ldap'
LATEST_BACKUP_DIR='/local/backup/latest'

[ -f ./sshcopy ] && source ./sshcopy || echo "sshcopy scripts are not available"

function backup_ldap() {
	local BAKFILE="$1"
	msg=`/etc/init.d/slapd stop`
	if [ $? -eq 0 ]; then
		msg=`/usr/sbin/slapcat | /bin/bzip2 > "$BAKFILE"`
		if [ $? -ne 0 ]; then
			echo "failed to backup OpenLDAP to $BAKFILE"
		fi
		msg=`/etc/init.d/slapd start`
		if [ $? -ne 0 ]; then
			echo "failed to start OpenLDAP server"
		fi
	else
		echo "failed to stop OpenLDAP server"
	fi
}

BAKFILE=$BACKUPDIR/ldap_`date +%Y%m%d`.bz2
backup_ldap "$BAKFILE"
RES=$?
if [ $RES -ne 0 ]; then
	echo "Failed to create backup of ldap to $BAKFILE"
	echo "Error: $msg"
else
	putmsg=`putremote $BAKFILE && remove_oldest "ldap_*"`
	if [ $? -ne 0 ]; then
		echo "$putmsg"
	fi
fi

cp "$BAKFILE" "$LATEST_BACKUP_DIR/fast-srv01_ldap.bz2"


