#!/bin/bash
#
# check_rkhunter - nagios plugin
#

# Include standard Nagios library
THIS_FILE=`readlink -f "$0"`
PROGNAME=`basename "$THIS_FILE"`
PROGPATH=`dirname "$THIS_FILE"`
RKHUNTER=/usr/bin/rkhunter
NICE=19

SELECTED_TESTS=''
# uncomment the following line to limit the testing to specific tests:
#SELECTED_TESTS='--enable attributes'

. $PROGPATH/utils.sh || exit 3

test -x $RKHUNTER || exit $STATE_UNKNOWN

msg=`/usr/bin/nice -n $NICE sudo $RKHUNTER --checkall --quiet --report-warnings-only --nocolors --skip-keypress --no-mail-on-warning $SELECTED_TESTS 2>&1`
RES=$?
if [ $RES -eq 0 ]; then
	RET=$STATE_OK
	PERF_DATA="infect=0 error=0 warning=0"
	RESULT="rkhunter: OK"
else
	stats=`echo "$msg" | awk 'BEGIN {warn=0; err=0; infect=0;} /Warning/ { warn=warn+1; } /Infect/ { infect=infect+1; } /Error/ { err=err+1; } END { print infect, err, warn}'`
	IFS=' ' read -a stats_elements <<< "$stats"
	additional_msg=''
	if [ "${stats_elements[0]}" -ne 0 ]; then
		RET=$STATE_CRITICAL
	elif [ "${stats_elements[1]}" -ne 0 ]; then
		RET=$STATE_CRITICAL
	elif [ "${stats_elements[2]}" -ne 0 ]; then
		RET=$STATE_WARNING
	else
		RET=$STATE_WARNING
		additional_msg='Unable to determine any errors and warnings '
	fi
	PERF_DATA="infect=${stats_elements[0]} error=${stats_elements[1]} warning=${stats_elements[2]}"
	RESULT="rkhunter: ${additional_msg}${stats_elements[0]} infections, ${stats_elements[1]} errors, ${stats_elements[2]} warnings"
fi

echo "$RESULT | $PERF_DATA"
exit $RET
