#!/bin/bash
scriptfile=`readlink -f "$0"`
scriptdir=`dirname "$scriptfile"`

FQDN=`hostname -f`
CONTACTEMAIL="root@$FQDN"
ADMINEMAIL=$CONTACTEMAIL
NOTIFICATIONTYPE='PROBLEM'
HOSTNAME="$FQDN"
HOSTALIAS=`hostname`
HOSTNOTES='Notes from my host'
HOSTSTATE='down'
HOSTSTATETYPE='N/A'
HOSTATTEMPT=1
MAXHOSTATTEMPTS=5
HOSTDURATION='1h'
HOSTNOTIFICATIONNUMBER=1
HOSTCHECKCOMMAND='check_alive'
HOSTLATENCY='1s'
LASTHOSTCHECK=`date +%s`
LASTHOSTSTATECHANGE=$LASTHOSTCHECK
LASTHOSTUP=$LASTHOSTCHECK
LASTHOSTDOWN=$LASTHOSTCHECK
LASTHOSTUNREACHABLE=$LASTHOSTCHECK
HOSTOUTPUT='My <home> was a [[castle]]'
HOSTADDRESS='127.0.0.1'
HOSTNOTESURL="http://127.0.0.1/icinga/cgi-bin/extinfo.cgi?type=1&host=$FQDN"
SERVICEDESC=''
SERVICESTATE='WARNING'
SERVICENOTIFICATIONNUMBER=1
SERVICEOUTPUT='foo'
LASTSERVICECHECK=`date +%s`
LASTSERVICESTATECHANGE=$LASTSERVICECHECK
LASTSERVICEOK=$LASTSERVICECHECK
LASTSERVICEWARNING=$LASTSERVICECHECK
LASTSERVICECRITICAL=$LASTSERVICECHECK
LASTSERVICEUNKNOWN=$LASTSERVICECHECK
SERVICESTATETYPE='down'
SERVICEATTEMPT=1
MAXSERVICEATTEMPTS=5
SERVICEDURATION='1h'
SERVICECHECKCOMMAND='check_service --with="quotes"'
SERVICEDISPLAYNAME='My <service> failed'
SERVICELATENCY='1s'
SERVICEPERCENTCHANGE=0
SERVICEACTIONURL='http://127.0.0.1/icinga/service/action'
SERVICENOTESURL="http://127.0.0.1/icinga/cgi-bin/extinfo.cgi?type=1&host=$FQDN&service=foo"
SERVICENOTES=''
TIMET=0
PROCESSSTARTTIME=0
TOTALHOSTSUP=0
TOTALHOSTSDOWN=0
TOTALHOSTSUNREACHABLE=0
TOTALSERVICESOK=0
TOTALSERVICESWARNING=0
TOTALSERVICESCRITICAL=0
TOTALSERVICESUNKNOWN=0
TOTALHOSTPROBLEMSUNHANDLED=0
TOTALSERVICEPROBLEMSUNHANDLED=0
NOTIFICATIONAUTHOR=`id -u`
NOTIFICATIONCOMMENT=`id`


#PNP4NAGIOS_URL="http://localhost/pnp4nagios/"
PNP4NAGIOS_URL=''

$scriptdir/icinga_mail.pl --debug 1 --smtphost 127.0.0.1 --icinga_url "http://localhost/icinga/" --pnp4nagios_url "$PNP4NAGIOS_URL" --originator "$ADMINEMAIL" --recipient "$CONTACTEMAIL" --notificationtype "$NOTIFICATIONTYPE" --adminemail "$ADMINEMAIL" --hostname "$HOSTNAME" --hostalias "$HOSTALIAS" --hostnotes "$HOSTNOTES" --hoststate "$HOSTSTATE" --hoststatetype "$HOSTSTATETYPE" --hostattempt "$HOSTATTEMPT" --maxhostattempt "$MAXHOSTATTEMPTS" --hostduration "$HOSTDURATION" --hostnotificationnumber "$HOSTNOTIFICATIONNUMBER" --hostcheckcommand "$HOSTCHECKCOMMAND" --hostlatency "$HOSTLATENCY" --lasthostcheck "$LASTHOSTCHECK" --lasthoststatechange "$LASTHOSTSTATECHANGE" --lasthostup "$LASTHOSTUP" --lasthostdown "$LASTHOSTDOWN" --lasthostunreachable "$LASTHOSTUNREACHABLE" --hostoutput "$HOSTOUTPUT" --hostaddress "$HOSTADDRESS" --hostnotesurl "$HOSTNOTESURL" --servicedesc "$SERVICEDESC" --servicestate "$SERVICESTATE" --servicenotificationnumber "$SERVICENOTIFICATIONNUMBER" --serviceoutput "$SERVICEOUTPUT" --lastservicecheck "$LASTSERVICECHECK" --lastservicestatechange "$LASTSERVICESTATECHANGE" --lastserviceok "$LASTSERVICEOK" --lastservicewarning "$LASTSERVICEWARNING" --lastservicecritical "$LASTSERVICECRITICAL" --lastserviceunknown "$LASTSERVICEUNKNOWN" --servicestatetype "$SERVICESTATETYPE" --serviceattempt "$SERVICEATTEMPT" --maxserviceattempts "$MAXSERVICEATTEMPTS" --serviceduration "$SERVICEDURATION" --servicecheckcommand "$SERVICECHECKCOMMAND" --servicedisplayname "$SERVICEDISPLAYNAME" --servicelatency "$SERVICELATENCY" --servicepercentchange "$SERVICEPERCENTCHANGE" --serviceactionurl "$SERVICEACTIONURL" --servicenotesurl "$SERVICENOTESURL" --servicenotes "$SERVICENOTES" --timet "$TIMET" --processstarttime "$PROCESSSTARTTIME" --totalhostsup "$TOTALHOSTSUP" --totalhostsdown "$TOTALHOSTSDOWN" --totalhostsunreachable "$TOTALHOSTSUNREACHABLE" --totalservicesok "$TOTALSERVICESOK" --totalserviceswarning "$TOTALSERVICESWARNING" --totalservicescritical "$TOTALSERVICESCRITICAL" --totalservicesunknown "$TOTALSERVICESUNKNOWN" --totalhostproblemsunhandled "$TOTALHOSTPROBLEMSUNHANDLED" --totalserviceproblemsunhandled "$TOTALSERVICEPROBLEMSUNHANDLED" --notificationauthor "$NOTIFICATIONAUTHOR" --notificationcomment "$NOTIFICATIONCOMMENT"
