#
# Makefile
#

all:

clean:

install:
	install -m 644 fastprotect_root_ca.pem $(CERTSDIR)/fastprotect_root_ca.crt
	install -m 644 fastprotect_ssl_ca.pem $(CERTSDIR)/fastprotect_ssl_ca.crt
	install -m 644 fastprotect_root_ca_sha256.pem $(CERTSDIR)/fastprotect_root_ca_sha256.crt
	install -m 644 fastprotect_ssl_ca_sha256.pem $(CERTSDIR)/fastprotect_ssl_ca_sha256.crt

