#!/bin/bash

apt_update_conf() {
	if [ "$new_domain_name" != "$old_domain_name" ]; then
		if [ ! -z "$new_domain_name" ]; then
			srv_record=`LANG=C /usr/bin/host -t SRV "_apt-proxy._tcp.$new_domain_name."`
			if [ $? -eq 0 ]; then
				srv_port=`echo "$srv_record" | awk '{ print $7 '}`
				srv_name=`echo "$srv_record" | awk '{ print $8 '}`
				newproxy="http://${srv_name%\.}:${srv_port}"
			else
				newproxy=''
			fi
		fi
		log_info "apt-proxy=$newproxy"
		verbose_exec "$scriptdir/apt-proxy" set "$newproxy"
	fi
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)                                                                                                                                                                           
		apt_update_conf
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
esac
