#!/bin/bash

CUPS_CLIENT_CONF='/etc/cups/client.conf'
CUPS_PRINTERS_CONF='/etc/cups/printers.conf'
DEFAULT_CUPS='/etc/default/cups'
BACKUP_DIR='/run/cups'
BACKUP_CUPS_CLIENT_CONF="$BACKUP_DIR/client.conf.bak"

CUPS_USE_DNS_INFO='auto'
[ -f "$DEFAULT_CUPS" ] && source "$DEFAULT_CUPS"

if [ "$CUPS_USE_DNS_INFO" == 'auto' ]; then
	if [ -f "$CUPS_PRINTERS_CONF" ]; then
		CUPS_USE_DNS_INFO=0
	else
		CUPS_USE_DNS_INFO=1
	fi
fi

cups_update_conf() {
	if [ ! -z "$new_domain_name" ]; then
		srv_record=`LANG=C /usr/bin/host -t SRV "_ipp._tcp.$new_domain_name."`
		if [ $? -eq 0 ]; then
			srv_port=`echo "$srv_record" | awk '{ print $7 }'`
			srv_name=`echo "$srv_record" | awk '{ print $8 }'`
			cups_server="${srv_name%\.}:${srv_port}"
		else
			cups_server=''
		fi
		
		cups_encryption=`get_dns_txt_record "_encryption._ipp._config.$new_domain_name."`
		[ -z "$cups_encryption" ] && cups_encryption=`awk '/^ *(Encryption)/ { print $2 }' "$CUPS_CLIENT_CONF"`
		[ -z "$cups_encryption" ] && cups_encryption='IfRequested'
	else
		cups_encryption=''
		cups_server=''
	fi
	log_info "cups_server $cups_server"
	log_info "cups_encryption $cups_encryption"
	
	if [ ! -z "$cups_server" -a ! -z "$cups_encryption" ]; then
		tmp=$(mktemp "$CUPS_CLIENT_CONF.XXXXXX") || return
		chmod --reference=$CUPS_CLIENT_CONF $tmp
		chown --reference=$CUPS_CLIENT_CONF $tmp
		#[ $verbose -ne 0 ] && echo "apply config from $CUPS_CLIENT_CONF to $tmp"
		(
			sed -r -e "s@^[ ]*ServerName[ ]+(.*)\$@ServerName $cups_server@" \
				-e "s@^[ #]*Encryption[ ]+(.*)\$@Encryption $cups_encryption@" \
				"$CUPS_CLIENT_CONF"
		) >>$tmp
		#[ $verbose -ne 0 ] && cat "$tmp"
		RES=$?
		if [ $RES -eq 0 ]; then
			[ ! -d "$BACKUP_DIR" ] && mkdir "$BACKUP_DIR"
			mv "$CUPS_CLIENT_CONF" "$BACKUP_CUPS_CLIENT_CONF"
			mv "$tmp" "$CUPS_CLIENT_CONF"
		fi
	fi
}

cups_restore_conf() {
	if [ -f "$BACKUP_CUPS_CLIENT_CONF" ]; then
		mv "$BACKUP_CUPS_CLIENT_CONF" "$CUPS_CLIENT_CONF"
	fi
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)  
		[ $CUPS_USE_DNS_INFO -ne 0 ] && cups_update_conf
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	NETWORK_UP)
		;;
	NETWORK_DOWN)
		cups_restore_conf
		;;
esac
