#!/bin/bash
KRB5_CONF='/etc/krb5.conf'
#KRB5_CONF_ORG='/var/run/krb5.conf'

heimdal_check_server() {
	if [ ! -z "$new_domain_name" ]; then
#		srv_record=`LANG=C /usr/bin/host -t SRV "_kerberos._tcp.$new_domain_name."`
#		if [ $? -eq 0 ]; then
#			srv_port=`echo "$srv_record" | awk '{ print $7 }'`
#			srv_name=`echo "$srv_record" | awk '{ print $8 }'`
#			newkerberosserver="${srv_name%\.}"
#		else
#			newkerberosserver=''
#		fi
#		srv_record=`LANG=C /usr/bin/host -t SRV "_kerberos-adm._tcp.$new_domain_name."`
#		if [ $? -eq 0 ]; then
#			srv_port=`echo "$srv_record" | awk '{ print $7 }'`
#			srv_name=`echo "$srv_record" | awk '{ print $8 }'`
#			newkerberosadmserver="${srv_name%\.}"
#		else
#			newkerberosadmserver=''
#		fi
		newrealm=`get_dns_txt_record "_kerberos.$new_domain_name."`
	fi

	if [ ! -z "$newrealm" ]; then
		log_info "newrealm=$newrealm"
		ini-util "$KRB5_CONF" --edit "libdefaults/default_realm=$newrealm"
		if [ $? -eq 0 ]; then
			mv "$tmp" "$KRB5_CONF"
		fi
	fi
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)                                                                                                                                                                           
		heimdal_check_server
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
	# events from network-manager
	up|vpn-up)
		heimdal_check_server
		;;
    down|vpn-down|hostname|dhcp4-change|dhcp6-change)
        ;;
esac
