#!/bin/bash

MAILNAME_FILE='/etc/mailname'
POSTFIX_CONFIG_DIR='/etc/postfix'

postfix_setup() {

	if [ -z "$new_host_name" ]; then
		# retrieve the current hostname
		myhostname=`hostname`
	else
		myhostname="$new_host_name"
	fi
	if [ ! -z "$new_domain_name" ]; then
		mailname="${myhostname}.${new_domain_name}"
		maildomain="${new_domain_name}"
	else
		mailname="${myhostname}"
		maildomain=""
	fi

	old_mailname=`cat "$MAILNAME_FILE"`
	log_info "old_mailname=$old_mailname"
	log_info "mailname=$mailname"
	log_info "maildomain=$maildomain"

	if [ "$old_mailname" != "$mailname" ]; then
		echo "$mailname" > $MAILNAME_FILE
		/usr/sbin/postconf -c "$POSTFIX_CONFIG_DIR" -e "myhostname=$mailname" "mydomain=$maildomain" && /usr/sbin/service postfix reload
	fi
}

case $reason in
	BOUND|RENEW|REBIND|REBOOT)                                                                                                                                                                           
		postfix_setup
		;;
	EXPIRE|FAIL|RELEASE|STOP)
		;;
esac
