#!/bin/bash

function usage() {
	echo "usage: apt-cleanup"
	echo "  this cleans up all temporary data used by apt."
	exit 0
}

# parse command line arguments
while [ $# -ne 0 ]; do
	case "$1" in
	"-?"|"-h"|"--help") usage;; 
	*)
		echo "Unrecognized parameter $1" 2>&1
		exit 1
	;;
	esac
	shift
done

if [[ $EUID -ne 0 ]]; then
	echo "You must be a root user" 2>&1
	exit 1
else
	/usr/bin/apt-get clean
	if [ -f /etc/apt/keylist -a -x /usr/bin/apt-key-import ]; then
		for f in /etc/apt/trust*; do
			[ -f "$f" ] && rm "$f"
		done
		/usr/bin/apt-key-import --keylist /etc/apt/keylist
	fi
	/usr/bin/find /var/lib/apt/lists -type f -print -delete
	/usr/bin/apt-get clean
	/usr/bin/apt-get update
fi
